"""
FAKENIX 2.0 — PDF Report Generation Service using ReportLab

Generates forensic analysis reports. Reports are stored in backend/storage/reports/.

Rules this module holds to:
  - A report is only created for a detection that exists. A missing detection
    or report is an error for the caller, never a reason to make one up.
  - Everything printed comes from the stored detection / evidence records or is
    measured from the stored evidence file. Missing values are shown as missing.
  - Every table has explicit column widths that fit the page and every cell is
    a Paragraph, so long text wraps instead of being clipped.

DISCLAIMER: These reports are generated by FAKENIX AI software and are
intended for informational purposes only. They do not constitute official
government evidence or legal documentation.
"""
import json
import os
import re
import uuid
from datetime import datetime, timezone
from functools import partial
from xml.sax.saxutils import escape

from flask import current_app
from sqlalchemy.exc import IntegrityError

from app.extensions import db
from app.models.report import Report
from app.models.detection import Detection
from app.models.evidence import Evidence
from app.services.hashing_service import calculate_sha256
from app.utils.logger import get_logger

logger = get_logger('report_service')

# Bump when the PDF layout or wording changes. A stored PDF from an older layout
# is rebuilt on its next download into a new file; the old file is left in place.
REPORT_LAYOUT_VERSION = 2

DETECTION_NOT_FOUND = 'Detection not found.'
VERDICTS = {'real': 'REAL', 'authentic': 'REAL', 'deepfake': 'FAKE', 'fake': 'FAKE', 'suspicious': 'SUSPICIOUS'}
GROQ_SUFFIX = ' (Groq)'
# What a filename extension claims, in Pillow's format names.
EXTENSION_FORMATS = {'.jpg': 'JPEG', '.jpeg': 'JPEG', '.png': 'PNG', '.webp': 'WEBP'}


# ──────────────────────────────────────────────────────────────
# Report records
# ──────────────────────────────────────────────────────────────

def generate_report(detection_uid: str, user=None) -> tuple[Report | None, str]:
    """
    Return the report for a detection, creating it (and its PDF) on first request.

    Args:
        detection_uid: Detection UID string or ID
        user: User object (or None for demo)

    Returns:
        (report, error_message)
    """
    ref = str(detection_uid)
    detection = db.session.query(Detection).filter(Detection.detection_uid == ref).first()
    if not detection and ref.isdigit():
        detection = db.session.query(Detection).filter(Detection.id == int(ref)).first()

    user_id = getattr(user, 'id', None)
    if detection and user_id and detection.user_id not in (None, user_id):
        detection = None  # someone else's detection
    if not detection:
        return None, DETECTION_NOT_FOUND
    if detection.status != 'complete' or not detection.result:
        return None, 'This detection has no completed analysis result to report on.'
    detection_id = detection.id

    report = _report_for_detection(detection_id)
    if not report:
        report = _create_report_record(detection_id, user)
        if not report:
            return None, 'Could not allocate a unique report ID. Please try again.'

    error = _generate_pdf_for_report(report, user)
    if error:
        return None, error
    return report, ''


def _report_for_detection(detection_id: int) -> Report | None:
    return db.session.query(Report).filter(Report.detection_id == detection_id).order_by(Report.id).first()


def _create_report_record(detection_id: int, user) -> Report | None:
    """
    Insert the report row, which reserves its ID, before any PDF is written.
    report_uid is UNIQUE: if a concurrent request took the proposed ID, the insert
    fails, and we either adopt the report that request created or try the next ID.
    """
    for _ in range(5):
        report = Report(
            report_uid=_next_report_uid(),
            user_id=getattr(user, 'id', None),
            detection_id=detection_id,
            report_type='Forensic Analysis',
            status='generating',
            generated_by=getattr(user, 'full_name', None) or 'FAKENIX System',
        )
        db.session.add(report)
        try:
            db.session.commit()
            logger.info(f'Report record created: {report.report_uid}')
            return report
        except IntegrityError:
            db.session.rollback()
            existing = _report_for_detection(detection_id)
            if existing:
                return existing
    return None


def _next_report_uid() -> str:
    """
    Propose the next FX-RPT-<year>-<n> ID. Numbers are never reissued: besides the
    IDs in the table, PDFs already in the report folder count as used, so an ID
    whose row was deleted cannot be given to another detection.
    """
    year = datetime.now(timezone.utc).year
    highest = 0
    uid_pattern = re.compile(rf'^FX-RPT-{year}-(\d+)$')
    for (uid,) in db.session.query(Report.report_uid).filter(Report.report_uid.like(f'FX-RPT-{year}-%')):
        match = uid_pattern.match(uid or '')
        if match:
            highest = max(highest, int(match.group(1)))
    file_pattern = re.compile(rf'^FX_RPT_{year}_(\d+)(?:_v\d+)?\.pdf$')
    try:
        for name in os.listdir(_report_folder()):
            match = file_pattern.match(name)
            if match:
                highest = max(highest, int(match.group(1)))
    except OSError:
        pass
    return f'FX-RPT-{year}-{highest + 1:03d}'


def get_all_reports(user_id: int = None) -> list:
    """Get all reports for a user (plus reports without an owner), or all reports."""
    query = db.session.query(Report)
    if user_id:
        query = query.filter((Report.user_id == user_id) | (Report.user_id == None))  # noqa: E711
    return [r.to_dict() for r in query.order_by(Report.created_at.desc()).all()]


def get_report_by_uid(report_uid: str, user_id: int = None) -> Report | None:
    """Get a single report by UID, if it is visible to the user."""
    uid = str(report_uid)
    report = db.session.query(Report).filter(Report.report_uid == uid).first()
    if not report and uid.startswith('rpt_') and uid[4:].isdigit():
        report = db.session.query(Report).filter(Report.id == int(uid[4:])).first()
    if report and user_id and report.user_id not in (None, user_id):
        return None
    return report


# ──────────────────────────────────────────────────────────────
# PDF files
# ──────────────────────────────────────────────────────────────

def _report_folder() -> str:
    return current_app.config.get('REPORT_FOLDER', 'storage/reports')


def _is_current_layout(filename: str | None) -> bool:
    return bool(filename) and filename.endswith(f'_v{REPORT_LAYOUT_VERSION}.pdf')


def get_report_path(report: Report) -> str | None:
    """
    Return the absolute path of the report PDF to serve, or None when it has to
    be (re)built first: the file is missing, or it is from an older layout and
    the detection it was built from still exists.
    """
    if not report or not report.report_path:
        return None
    full_path = os.path.join(_report_folder(), os.path.basename(report.report_path))
    if not os.path.exists(full_path):
        return None
    if _is_current_layout(report.report_path) or report.detection is None:
        return full_path
    return None


def _generate_pdf_for_report(report: Report, user=None) -> str:
    """
    Make sure the report has a current PDF on disk, building it under the
    report's existing ID if needed. Returns '' on success or an error message.
    Never creates detection or evidence records.
    """
    if get_report_path(report):
        return ''

    detection = report.detection
    if detection is None:
        return 'The detection this report was generated from no longer exists.'
    evidence = detection.evidence.order_by(Evidence.id).first()

    # A new file name per layout version: an existing PDF is never overwritten.
    filename = f'{report.report_uid.replace("-", "_")}_v{REPORT_LAYOUT_VERSION}.pdf'
    os.makedirs(_report_folder(), exist_ok=True)
    error = _generate_pdf(os.path.join(_report_folder(), filename), report, detection, evidence)
    if error:
        report.status = 'error'
        db.session.commit()
        return error

    report.report_path = filename
    report.status = 'ready'
    db.session.commit()
    logger.info(f'Report PDF written: {filename}')
    return ''


# ──────────────────────────────────────────────────────────────
# Report content (read from the stored records)
# ──────────────────────────────────────────────────────────────

def _utc(dt: datetime | None) -> str | None:
    """Format a datetime as UTC. Naive values are UTC already (that is how they are stored)."""
    if dt is None:
        return None
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime('%Y-%m-%d %H:%M:%S')


def _load_json(text, expected):
    try:
        value = json.loads(text) if text else None
    except (TypeError, ValueError):
        value = None
    return value if isinstance(value, expected) else expected()


def _format_bytes(size: int) -> str:
    if size < 1024:
        return f'{size} B'
    if size < 1024 * 1024:
        return f'{size / 1024:.1f} KB'
    return f'{size / 1024 / 1024:.2f} MB'


def _stored_evidence_path(evidence: Evidence | None) -> str | None:
    """Absolute path of the stored evidence file, if it is on disk."""
    if not evidence or not evidence.file_path:
        return None
    path = os.path.join(current_app.config.get('UPLOAD_FOLDER', ''), os.path.basename(evidence.file_path))
    return path if os.path.isfile(path) else None


def check_evidence_integrity(evidence: Evidence | None) -> dict:
    """
    Re-hash the stored evidence file and compare it with the SHA-256 recorded at
    upload. Read-only: the evidence record is not modified.

    'state' is one of: match, mismatch, unavailable, no_hash, no_evidence.
    """
    if evidence is None:
        return {'state': 'no_evidence', 'short': 'NO EVIDENCE FILE',
                'label': 'NO EVIDENCE FILE — no evidence record exists for this detection, '
                         'so there is no file hash to verify.'}

    result = {'sha256': evidence.sha256_hash or None, 'md5': evidence.md5_hash or None,
              'recorded_at': _utc(evidence.created_at)}
    if not evidence.sha256_hash:
        return {**result, 'state': 'no_hash', 'short': 'NOT VERIFIED',
                'label': 'NOT VERIFIED — no SHA-256 hash was recorded for this evidence.'}

    path = _stored_evidence_path(evidence)
    try:
        actual = calculate_sha256(path) if path else None
    except Exception:
        actual = None
    if not actual:
        return {**result, 'state': 'unavailable', 'short': 'NOT VERIFIED',
                'label': 'NOT VERIFIED — the stored evidence file is not available, so the recorded hash '
                         'could not be re-checked.'}

    checked_at = _utc(datetime.now(timezone.utc))
    if actual.lower() == evidence.sha256_hash.lower():
        return {**result, 'state': 'match', 'short': 'HASH MATCH',
                'label': f'MATCH — the stored evidence file was re-hashed on {checked_at} UTC and its SHA-256 '
                         'equals the recorded value.'}
    return {**result, 'state': 'mismatch', 'short': 'HASH MISMATCH', 'actual_sha256': actual,
            'label': f'MISMATCH — the stored evidence file was re-hashed on {checked_at} UTC and its SHA-256 '
                     'differs from the recorded value. The stored file has been changed or replaced since '
                     'the hash was recorded.'}


def _measure_stored_file(path: str | None, file_type: str) -> dict:
    """Size, and for images the real format, read from the stored evidence file itself."""
    measured = {}
    if not path:
        return measured
    try:
        measured['size_bytes'] = os.path.getsize(path)
        if file_type == 'image':
            from PIL import Image
            with Image.open(path) as img:
                measured['format'] = 'JPEG' if img.format == 'MPO' else img.format
                measured['mime'] = Image.MIME.get(img.format)
                measured['dimensions'] = f'{img.width} × {img.height} px'
    except Exception as e:
        logger.warning(f'Could not measure stored evidence file: {e}')
    return measured


def build_report_context(report: Report, detection: Detection, evidence: Evidence | None) -> dict:
    """Everything the PDF prints, taken from the stored report, detection and evidence."""
    meta = _load_json(detection.metadata_json, dict)
    is_demo = bool(detection.is_demo)
    file_type = detection.file_type or ''

    # Detection.confidence and Detection.deepfake_probability hold the same value:
    # the 0-100 likelihood that the media is FAKE. real_probability is 100 minus it.
    deepfake = detection.deepfake_probability if detection.deepfake_probability is not None else detection.confidence
    authentic = detection.real_probability
    if authentic is None and deepfake is not None:
        authentic = round(100 - deepfake, 1)

    stored_model = detection.model_name or None
    if is_demo:
        analysis_type = 'Simulated demo result — no model inference was run'
        provider = 'None (no inference provider was called)'
        model = f'None (stored label: "{stored_model}")' if stored_model else 'None'
        source = None
    else:
        analysis_type = 'AI model inference (vision language model)'
        from_groq = bool(stored_model) and stored_model.endswith(GROQ_SUFFIX)
        provider = 'Groq Cloud' if from_groq else None
        model = stored_model[:-len(GROQ_SUFFIX)] if from_groq else stored_model
        source = ' via '.join(part for part in (model, provider) if part) or 'the analysing model'

    # File facts: measured from the stored file when it exists, else as recorded at upload.
    stored_path = _stored_evidence_path(evidence)
    measured = _measure_stored_file(stored_path, file_type)
    extension = os.path.splitext(detection.file_name or '')[1].lower() or None
    file_format = measured.get('format') or meta.get('format')
    size_bytes = measured.get('size_bytes', meta.get('fileSizeBytes'))
    if size_bytes is not None:
        file_size = f'{_format_bytes(size_bytes)} ({size_bytes:,} bytes)'
    else:
        file_size = detection.file_size if re.search(r'\d\s*(B|KB|MB|GB)$', detection.file_size or '') else None
    width, height = meta.get('width'), meta.get('height')
    dimensions = measured.get('dimensions') or (f'{width} × {height} px' if width and height else detection.resolution)

    inconsistencies = []
    claimed = EXTENSION_FORMATS.get(extension or '')
    if file_type == 'image' and claimed and file_format and claimed != file_format:
        inconsistencies.append(f'Filename extension "{extension}" indicates {claimed}, '
                               f'but the file content is {file_format}.')

    indicators = []
    for item in _load_json(detection.indicators_json, list):
        if not isinstance(item, dict) or not str(item.get('name') or '').strip():
            continue
        score = item.get('score')
        if isinstance(score, bool) or not isinstance(score, (int, float)):
            score = None
        elif score > 1:  # stored on a 0-100 scale
            score = score / 100
        indicators.append({'name': item['name'], 'score': score,
                           'severity': item.get('severity'), 'evidence': item.get('evidence')})

    thresholds = current_app.config.get('RISK_THRESHOLDS', {})
    low_max = thresholds.get('low', (0.0, 30.0))[1]
    medium_max = thresholds.get('suspicious', (30.0, 70.0))[1]
    verdict = VERDICTS.get((detection.result or '').lower(), 'UNDETERMINED')
    notes = []
    if deepfake is None:
        notes.append('No deepfake probability is stored for this detection.')
    elif (verdict == 'REAL' and deepfake >= low_max) or (verdict == 'FAKE' and deepfake < low_max):
        notes.append(f'The stored verdict ({verdict}) is not consistent with the stored deepfake probability '
                     f'({deepfake:.1f}%). Treat this result as inconclusive.')

    return {
        'report_id': report.report_uid,
        'generated_at': _utc(report.created_at),
        'generated_by': report.generated_by or 'FAKENIX System',
        'evidence_id': evidence.evidence_uid if evidence else None,
        'detection_id': detection.detection_uid,
        'is_demo': is_demo,
        'verdict': verdict,
        'risk_level': detection.risk_level,
        'deepfake_probability': deepfake,
        'authentic_probability': authentic,
        'risk_bands': (f'below {low_max:.0f}% low, {low_max:.0f}–{medium_max:.0f}% medium, '
                       f'{medium_max:.0f}% and above high, 95% and above critical'),
        'notes': notes,
        'file_name': None if file_type == 'url' else detection.file_name,
        'source_url': (detection.source_url or detection.file_name) if file_type == 'url' else None,
        'file_type': file_type.upper() or None,
        'file_size': file_size,
        'dimensions': dimensions,
        'duration': (detection.duration or meta.get('duration') or 'Not determined') if file_type == 'video' else None,
        'uploaded_at': _utc(detection.created_at),
        'measured_from_file': bool(measured),
        'integrity': check_evidence_integrity(evidence),
        'metadata': {
            'extension': extension if file_type != 'url' else None,
            'format': file_format,
            # Only a MIME type derived from the file content; never the filename's guess.
            'mime': measured.get('mime'),
            'mode': meta.get('mode'),
            'fps': f'{meta["fps"]} fps' if meta.get('fps') else None,
            'codec': meta.get('codec'),
            'exif': {True: 'None present', False: 'Present'}.get(meta.get('exifStripped')),
            'software': meta.get('softwareTag') if meta.get('softwareTag') not in ('Unknown', '') else None,
            'created': meta.get('created'),
            'inconsistencies': inconsistencies,
        },
        'indicators': indicators,
        'frames': [f for f in _load_json(detection.frames_json, list) if isinstance(f, dict)] if file_type == 'video' else [],
        'analysis_type': analysis_type,
        'model': model,
        'provider': provider,
        'source': source,
        'observations': None if is_demo else (meta.get('aiExplanation') or None),
    }


# ──────────────────────────────────────────────────────────────
# PDF layout
# ──────────────────────────────────────────────────────────────

def _generate_pdf(path: str, report: Report, detection: Detection, evidence: Evidence | None) -> str:
    """
    Render the report with ReportLab.
    Returns empty string on success, error message on failure.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate
    except ImportError:
        msg = 'ReportLab is not installed. Run: uv sync'
        logger.error(msg)
        return msg

    # Written under a temporary name and moved into place, so a failed build
    # never leaves a half-written PDF under the final name.
    tmp_path = f'{path}.{uuid.uuid4().hex}.tmp'
    try:
        from reportlab.lib.units import mm
        ctx = build_report_context(report, detection, evidence)
        footer = f'FAKENIX Forensic Analysis Report  ·  {ctx["report_id"]}'
        if ctx['is_demo']:
            footer += '  ·  DEMO / SIMULATED'
        doc = SimpleDocTemplate(
            tmp_path, pagesize=A4,
            leftMargin=18 * mm, rightMargin=18 * mm, topMargin=18 * mm, bottomMargin=22 * mm,
            title=f'FAKENIX Forensic Analysis Report {ctx["report_id"]}', author='FAKENIX',
        )
        # Frames pad their content by 6pt on each side; tables sized to this line up with the text.
        content_width = doc.width - 12
        doc.build(build_story(ctx, content_width), canvasmaker=partial(_numbered_canvas_class(), footer_text=footer))
        os.replace(tmp_path, path)
        return ''
    except Exception as e:
        logger.exception(f'PDF generation error for {report.report_uid}: {e}')
        return 'Report PDF generation failed.'
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def _numbered_canvas_class():
    """Canvas that draws the footer with 'Page X of Y' once the page count is known."""
    from reportlab.lib.colors import HexColor
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    class NumberedCanvas(canvas.Canvas):
        def __init__(self, *args, footer_text: str = '', **kwargs):
            super().__init__(*args, **kwargs)
            self._footer_text = footer_text.encode('cp1252', 'replace').decode('cp1252')
            self._page_states = []

        def showPage(self):
            self._page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            total = len(self._page_states)
            for state in self._page_states:
                self.__dict__.update(state)
                width = self._pagesize[0]
                self.saveState()
                self.setStrokeColor(HexColor('#cbd5e1'))
                self.setLineWidth(0.5)
                self.line(18 * mm, 16 * mm, width - 18 * mm, 16 * mm)
                self.setFont('Helvetica', 7.5)
                self.setFillColor(HexColor('#475569'))
                self.drawString(18 * mm, 12 * mm, self._footer_text)
                self.drawRightString(width - 18 * mm, 12 * mm, f'Page {self._pageNumber} of {total}')
                self.restoreState()
                super().showPage()
            super().save()

    return NumberedCanvas


def build_story(ctx: dict, content_width: float) -> list:
    """The report as ReportLab flowables for a frame `content_width` points wide."""
    from reportlab.lib.colors import HexColor
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import HRFlowable, KeepTogether, Paragraph, Spacer, Table, TableStyle

    brand_primary = HexColor('#4f46e5')
    brand_purple = HexColor('#7c3aed')
    grey_text = HexColor('#475569')
    dark_text = HexColor('#0f172a')
    grid = HexColor('#cbd5e1')
    label_bg = HexColor('#f1f5f9')
    header_bg = HexColor('#e2e8f0')
    red, amber, green = HexColor('#dc2626'), HexColor('#d97706'), HexColor('#16a34a')
    warn_bg, warn_border, warn_text = HexColor('#fff7ed'), HexColor('#ea580c'), HexColor('#7c2d12')

    title_style = ParagraphStyle('fx_title', fontName='Helvetica-Bold', fontSize=22, leading=26, textColor=brand_primary)
    subtitle_style = ParagraphStyle('fx_subtitle', fontName='Helvetica-Bold', fontSize=10, leading=13,
                                    textColor=brand_purple, spaceAfter=5)
    h2_style = ParagraphStyle('fx_h2', fontName='Helvetica-Bold', fontSize=12, leading=15, textColor=brand_primary,
                              spaceBefore=12, spaceAfter=5, keepWithNext=1)
    label_style = ParagraphStyle('fx_label', fontName='Helvetica', fontSize=8.5, leading=11.5, textColor=dark_text)
    value_style = ParagraphStyle('fx_value', fontName='Helvetica-Bold', fontSize=8.5, leading=11.5, textColor=dark_text)
    body_style = ParagraphStyle('fx_body', fontName='Helvetica', fontSize=8.5, leading=12, textColor=dark_text)
    head_style = ParagraphStyle('fx_head', fontName='Helvetica-Bold', fontSize=8.5, leading=11.5, textColor=dark_text)
    note_style = ParagraphStyle('fx_note', fontName='Helvetica', fontSize=7.5, leading=10.5, textColor=grey_text)
    mono_style = ParagraphStyle('fx_mono', fontName='Courier', fontSize=8, leading=11, textColor=dark_text)
    warn_style = ParagraphStyle('fx_warn', fontName='Helvetica', fontSize=8.5, leading=12, textColor=warn_text)
    disclaimer_style = ParagraphStyle('fx_disclaimer', fontName='Helvetica', fontSize=7.5, leading=11, textColor=grey_text)

    not_recorded = 'Not recorded'

    def t(value) -> str:
        """Dynamic text made safe for a Paragraph: escaped, and limited to the built-in fonts' character set."""
        text = '' if value is None else str(value)
        return escape(text.encode('cp1252', 'replace').decode('cp1252'))

    def p(value, style=value_style):
        return Paragraph(t(value), style)

    def pct(value) -> str:
        return not_recorded if value is None else f'{float(value):.1f}%'

    def colored(text, color, parent=value_style):
        return Paragraph(t(text), ParagraphStyle('fx_colored', parent=parent, textColor=color))

    def grid_style(extra=()):
        return TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, grid),
            ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4), ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            *extra,
        ])

    def present(pairs):
        """Drop label/value pairs whose value is missing, so no empty field is printed."""
        return [(label, value) for label, value in pairs if value not in (None, '')]

    def as_cell(value):
        """A value may be text or a ready-made Paragraph."""
        return value if hasattr(value, 'wrap') else p(value)

    def kv_table(rows, label_width=42 * mm):
        """Two-column label/value table."""
        data = [[p(label, label_style), as_cell(value)] for label, value in rows]
        table = Table(data, colWidths=[label_width, content_width - label_width])
        table.setStyle(grid_style([('BACKGROUND', (0, 0), (0, -1), label_bg)]))
        return table

    def pairs_table(pairs, label_width=32 * mm):
        """Four-column table holding two label/value pairs per row."""
        value_width = content_width / 2 - label_width
        data, extra = [], [('BACKGROUND', (0, 0), (0, -1), label_bg)]
        for i in range(0, len(pairs), 2):
            row = [p(pairs[i][0], label_style), as_cell(pairs[i][1])]
            if i + 1 < len(pairs):
                row += [p(pairs[i + 1][0], label_style), as_cell(pairs[i + 1][1])]
                extra.append(('BACKGROUND', (2, len(data)), (2, len(data)), label_bg))
            else:
                row += ['', '']  # an odd last pair spans the row instead of leaving empty cells
                extra.append(('SPAN', (1, len(data)), (3, len(data))))
            data.append(row)
        table = Table(data, colWidths=[label_width, value_width, label_width, value_width])
        table.setStyle(grid_style(extra))
        return table

    def box(flowables, background, border):
        table = Table([[flowables]], colWidths=[content_width])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), background), ('BOX', (0, 0), (-1, -1), 0.8, border),
            ('LEFTPADDING', (0, 0), (-1, -1), 8), ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 7), ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ]))
        return table

    def header_table(headers, rows, widths):
        data = [[p(h, head_style) for h in headers]] + rows
        table = Table(data, colWidths=widths, repeatRows=1)
        table.setStyle(grid_style([('BACKGROUND', (0, 0), (-1, 0), header_bg)]))
        return table

    is_demo = ctx['is_demo']
    verdict = ctx['verdict']
    verdict_color, verdict_bg = {
        'REAL': (green, HexColor('#f0fdf4')), 'FAKE': (red, HexColor('#fef2f2')),
        'SUSPICIOUS': (amber, HexColor('#fffbeb')),
    }.get(verdict, (grey_text, label_bg))
    integrity = ctx['integrity']
    integrity_color = {'match': green, 'mismatch': red}.get(integrity['state'], amber)
    story = []

    # ── Header ──────────────────────────────────────────────
    story.append(Paragraph('FAKENIX', title_style))
    story.append(Paragraph('AI-Powered Deepfake Detection &amp; Digital Forensics', subtitle_style))
    story.append(HRFlowable(width='100%', color=brand_primary, thickness=2, spaceAfter=8))
    if is_demo:
        story.append(box([Paragraph(
            '<b>DEMO / SIMULATED ANALYSIS.</b> This result was produced by the application\'s demo mode. '
            'No AI model analysed this media. The verdict, probabilities and indicators below are illustrative '
            'placeholders and must not be relied on for any decision.', warn_style)], warn_bg, warn_border))
        story.append(Spacer(1, 3 * mm))

    # ── 1. Report Information ───────────────────────────────
    story.append(Paragraph('Report Information', h2_style))
    story.append(pairs_table([
        ('Report ID', ctx['report_id']),
        ('Generated (UTC)', ctx['generated_at'] or not_recorded),
        ('Report Type', 'Forensic Analysis Report'),
        ('Generated By', ctx['generated_by']),
        ('Evidence ID', ctx['evidence_id'] or 'None (no evidence file)'),
        ('Integrity Check', colored(integrity['short'], integrity_color)),
    ]))

    # ── 2. Detection Result ─────────────────────────────────
    story.append(Paragraph('Detection Result', h2_style))
    verdict_note = {
        'REAL': 'The model reported no meaningful signs of manipulation. This is a model assessment, '
                'not proof that the media is authentic.',
        'FAKE': 'The model reported signs of manipulation or AI generation. This is a model assessment, '
                'not proof of manipulation.',
        'SUSPICIOUS': 'The assessment is inconclusive: the evidence is weak, mixed or contradictory. '
                      'The media is neither confirmed authentic nor confirmed manipulated.',
    }.get(verdict, 'No verdict is stored for this detection.')
    if is_demo:
        verdict_note = 'Simulated demo result — no model analysed this media.'
    story.append(box([
        Paragraph(f'VERDICT: {t(verdict)}', ParagraphStyle('fx_verdict', fontName='Helvetica-Bold', fontSize=16,
                                                            leading=20, alignment=TA_CENTER, textColor=verdict_color)),
        Spacer(1, 2),
        Paragraph(t(verdict_note), ParagraphStyle('fx_verdict_note', parent=body_style, alignment=TA_CENTER)),
    ], verdict_bg, verdict_color))
    story.append(Spacer(1, 2 * mm))
    risk = (ctx['risk_level'] or '').lower()
    story.append(kv_table([
        ('Deepfake Probability', pct(ctx['deepfake_probability'])),
        ('Authentic Probability', pct(ctx['authentic_probability'])),
        ('Risk Level', colored(risk.upper() or not_recorded,
                               {'low': green, 'medium': amber, 'high': red, 'critical': red}.get(risk, dark_text))),
    ]))
    for note in ctx['notes']:
        story.append(Spacer(1, 1.5 * mm))
        story.append(Paragraph(f'<b>Note:</b> {t(note)}', body_style))
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph(
        ('<b>These values were simulated by demo mode and measure nothing about this media.</b> ' if is_demo else '')
        + '<b>How to read these values.</b> <i>Deepfake probability</i> is the analysing model\'s own 0–100% '
        'estimate that the media is fake (0% = certainly real, 100% = certainly fake). A low value therefore '
        'supports a REAL verdict. It is a self-reported judgement, not a statistically calibrated probability. '
        '<i>Authentic probability</i> is 100% minus that value, not a separate measurement. <i>Risk level</i> '
        f'is derived from the deepfake probability ({t(ctx["risk_bands"])}).', note_style))

    # ── 3. File Information ─────────────────────────────────
    story.append(Paragraph('File Information', h2_style))
    story.append(pairs_table(present([
        ('File Name', ctx['file_name']),
        ('Source URL', ctx['source_url']),
        ('File Size', ctx['file_size']),
        ('File Type', ctx['file_type']),
        ('Dimensions', ctx['dimensions']),
        ('Uploaded (UTC)', ctx['uploaded_at']),
        ('Duration', ctx['duration']),
    ])))
    story.append(Spacer(1, 1.5 * mm))
    story.append(Paragraph(
        'File size and image dimensions were measured from the stored evidence file for this report. '
        'The file name is as supplied by the uploader.' if ctx['measured_from_file'] else
        'The stored evidence file was not available when this report was generated; values are as recorded '
        'at upload and could not be re-measured.', note_style))

    # ── 4. Cryptographic Integrity ──────────────────────────
    integrity_rows = []
    if integrity.get('sha256'):
        integrity_rows.append(('SHA-256 Hash (recorded)', p(integrity['sha256'], mono_style)))
    if integrity.get('md5'):
        integrity_rows.append(('MD5 Hash (reference only)', p(integrity['md5'], mono_style)))
    if integrity.get('recorded_at'):
        integrity_rows.append(('Hash Recorded (UTC)', integrity['recorded_at']))
    integrity_rows.append(('Integrity Check', colored(integrity['label'], integrity_color)))
    if integrity.get('actual_sha256'):
        integrity_rows.append(('SHA-256 Hash (stored file now)', p(integrity['actual_sha256'], mono_style)))
    story.append(KeepTogether([
        Paragraph('Cryptographic Integrity', h2_style),
        kv_table(integrity_rows),
        Spacer(1, 1.5 * mm),
        Paragraph(
            'A matching hash shows only that the file held by FAKENIX is byte-for-byte identical to the file that '
            'was hashed when the evidence record was created. It does not show that the media is genuine or was '
            'unaltered before upload. MD5 is listed for cross-referencing only and is not collision-resistant.',
            note_style),
    ]))

    # ── 5. Metadata Analysis ────────────────────────────────
    metadata = ctx['metadata']
    story.append(Paragraph('Metadata Analysis', h2_style))
    metadata_rows = present([
        ('Filename Extension', metadata['extension']),
        ('Detected Format', metadata['format']),
        ('MIME Type (from content)', metadata['mime']),
        ('Colour Mode', metadata['mode']),
        ('Frame Rate', metadata['fps']),
        ('Video Codec', metadata['codec']),
        ('EXIF Metadata', metadata['exif']),
        ('Software Tag', metadata['software']),
        ('Capture / Creation Time', metadata['created']),
    ])
    if metadata_rows:
        story.append(pairs_table(metadata_rows, label_width=40 * mm))
    else:
        story.append(Paragraph('No metadata is stored for this detection.', body_style))
    for issue in metadata['inconsistencies']:
        story.append(Spacer(1, 1.5 * mm))
        story.append(box([Paragraph(f'<b>Metadata inconsistency:</b> {t(issue)}', warn_style)], warn_bg, warn_border))

    # ── 6. Forensic Analysis ────────────────────────────────
    story.append(Paragraph('Forensic Analysis', h2_style))
    if ctx['indicators']:
        rows = []
        for ind in ctx['indicators']:
            cell = [p(ind['name'])]
            if ind.get('evidence'):
                cell.append(p(ind['evidence'], body_style))
            rows.append([cell,
                         p('Not given' if ind['score'] is None else f'{ind["score"] * 100:.0f}%', body_style),
                         p((ind.get('severity') or 'Not given').upper(), body_style)])
        story.append(header_table(['Forensic Indicator / Anomaly', 'Anomaly Score', 'Severity'], rows,
                                  [content_width - 60 * mm, 32 * mm, 28 * mm]))
    else:
        story.append(Paragraph(
            'No indicators are stored for this demo result.' if is_demo else
            'The model reported no specific manipulation indicators for this media.', body_style))
    if ctx['frames']:
        story.append(Spacer(1, 2.5 * mm))
        rows = [[p(f.get('frameNum'), body_style), p(f.get('timestamp') or not_recorded, body_style),
                 p(pct(f.get('probability')), body_style),
                 p('; '.join(str(a) for a in f.get('anomalies') or []) or 'None given', body_style)]
                for f in ctx['frames']]
        story.append(header_table(['Frame', 'Timestamp', 'Deepfake Probability', 'Model Notes'], rows,
                                  [20 * mm, 24 * mm, 36 * mm, content_width - 80 * mm]))
    story.append(Spacer(1, 1.5 * mm))
    story.append(Paragraph(
        '<b>Source:</b> ' + ('Simulated by demo mode. Not produced by any model and not measured from the media.'
                             if is_demo else
                             f'AI-generated observations reported by {t(ctx["source"])}. Anomaly scores are the '
                             'model\'s own ratings. FAKENIX did not independently measure or verify them.'),
        note_style))

    # ── 7. AI Inference Analysis ────────────────────────────
    story.append(Paragraph('AI Inference Analysis', h2_style))
    story.append(kv_table([
        ('AI Model', ctx['model'] or not_recorded),
        ('Inference Provider', ctx['provider'] or not_recorded),
        ('Analysis Type', ctx['analysis_type']),
        ('Classification Verdict', f'{verdict} — deepfake probability {pct(ctx["deepfake_probability"])}'),
    ]))

    # ── 8. Observations & Findings ──────────────────────────
    story.append(Paragraph('Observations &amp; Findings', h2_style))
    if ctx['observations']:
        story.append(box([Paragraph(t(ctx['observations']), body_style)], label_bg, grid))
        story.append(Spacer(1, 1.5 * mm))
        story.append(Paragraph(
            f'<b>Source:</b> Written assessment returned by {t(ctx["source"])}, reproduced as stored. It is the '
            'model\'s opinion, not an independently verified forensic finding.', note_style))
    else:
        story.append(Paragraph(
            'No written observations exist for a demo result.' if is_demo else
            'No written observations were stored for this detection.', body_style))

    # ── 9. Legal Disclaimer ─────────────────────────────────
    story.append(KeepTogether([
        Paragraph('Legal Disclaimer', h2_style),
        box([Paragraph(
            'This report is generated automatically by FAKENIX software for investigation support, awareness and '
            'research. The verdict is an automated assessment by an AI model and can be wrong in either '
            'direction. This report is not an official government document, a certificate of authenticity, or '
            'expert testimony, and it does not by itself establish that any media is genuine or manipulated. '
            'Findings should be reviewed by a qualified human examiner before being relied on in legal, '
            'disciplinary or other consequential proceedings.', disclaimer_style)], label_bg, grid),
    ]))
    return story
